# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-15 16:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=12)),
                ('sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=2)),
                ('date_of_birth', models.DateField()),
                ('occupation', models.CharField(max_length=50)),
                ('monthly_family_income', models.IntegerField()),
                ('no_earners', models.IntegerField()),
                ('address', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estimated_amount', models.IntegerField(default=0)),
                ('self_amount', models.IntegerField(default=0)),
                ('ouruma_expected', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('N', 'New'), ('S', 'Submited'), ('R', 'Review'), ('A', 'Accepted'), ('RJ', 'Rejected')], default='N', max_length=10)),
                ('created', models.DateField(auto_now_add=True)),
                ('updated', models.DateField(auto_now=True)),
                ('application_number', models.CharField(max_length=60)),
                ('Applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oruma.Applicant')),
            ],
        ),
        migrations.CreateModel(
            name='ApplicationNotes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(null=True)),
                ('created', models.DateField(auto_now=True)),
                ('Application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oruma.Application')),
            ],
        ),
        migrations.CreateModel(
            name='Dependend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('relation', models.CharField(max_length=50, null=True)),
                ('age', models.IntegerField()),
                ('occupation', models.CharField(max_length=50, null=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oruma.Applicant')),
            ],
        ),
        migrations.CreateModel(
            name='Detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aid_type', models.CharField(max_length=200)),
                ('add_information', models.CharField(max_length=500)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oruma.Application')),
            ],
        ),
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
                ('document', models.FileField(upload_to='application/files')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oruma.Application')),
            ],
        ),
        migrations.CreateModel(
            name='Recommender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=12)),
                ('email', models.EmailField(max_length=80)),
                ('address', models.TextField(max_length=300)),
            ],
        ),
        migrations.AddField(
            model_name='application',
            name='Recommender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oruma.Recommender'),
        ),
    ]
