# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-12 07:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oruma', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='address',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
