# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-15 17:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oruma', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='monthly_family_income',
            field=models.IntegerField(default=1000),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='no_earners',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='dependend',
            name='age',
            field=models.IntegerField(default=10),
        ),
    ]
