# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-22 10:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oruma', '0002_auto_20170415_2236'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='payment_frequency',
            field=models.CharField(choices=[('MN', 'Monthly'), ('WK', 'Full Payment'), ('PP', 'Part Payment')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='payment_mode',
            field=models.CharField(choices=[('CK', 'Check'), ('CS', 'Cash'), ('DD', 'DD')], max_length=50, null=True),
        ),
    ]
