# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-12 07:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oruma', '0002_applicant_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='recommender',
            new_name='Recommender',
        ),
        migrations.AddField(
            model_name='application',
            name='app_stage',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='application',
            name='estimated_amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='application',
            name='ouruma_expected',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='application',
            name='self_amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('N', 'New'), ('S', 'Submited'), ('R', 'Review'), ('A', 'Accepted'), ('RJ', 'Rejected')], default='N', max_length=10),
        ),
        migrations.AlterField(
            model_name='recommender',
            name='address',
            field=models.TextField(max_length=300),
        ),
    ]
