# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-15 04:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oruma', '0003_auto_20170312_1310'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dependend',
            name='date_of_birth',
        ),
        migrations.AddField(
            model_name='dependend',
            name='age',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dependend',
            name='occupation',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='dependend',
            name='relation',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
