# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-23 12:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oruma', '0003_auto_20170422_1603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('New', 'New'), ('Submitted', 'Submitted'), ('Review', 'Review'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected')], default='N', max_length=10),
        ),
    ]
