# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-23 12:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oruma', '0004_auto_20170423_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='payment_frequency',
            field=models.CharField(choices=[('Monthly', 'Monthly'), ('Full', 'Full'), ('Part', 'Part')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='payment_mode',
            field=models.CharField(choices=[('Check', 'Check'), ('Cash', 'Cash'), ('DD', 'DD')], max_length=50, null=True),
        ),
    ]
