# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-08 08:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oruma', '0004_auto_20170315_1019'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationNotes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(null=True)),
                ('created', models.DateField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='application',
            name='app_stage',
        ),
        migrations.AddField(
            model_name='application',
            name='application_number',
            field=models.CharField(default=1, max_length=60),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='applicationnotes',
            name='Application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oruma.Application'),
        ),
    ]
