# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-23 12:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oruma', '0005_auto_20170423_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('New', 'New'), ('Submitted', 'Submitted'), ('Review', 'Review'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='N', max_length=10),
        ),
    ]
