# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-08 09:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oruma', '0006_application_create_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='create_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
