# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-25 14:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oruma', '0007_auto_20170425_2015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dependend',
            name='age',
            field=models.IntegerField(null=True),
        ),
    ]
