# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-25 14:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oruma', '0008_auto_20170425_2017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='enquiry_notes',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='enquiry_team',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='extra_notes',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='payment_details',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
