# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-08 10:25
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('oruma', '0008_auto_20170408_1443'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='create_by',
        ),
        migrations.AddField(
            model_name='application',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
